services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: quantera
      POSTGRES_USER: quantera
      POSTGRES_PASSWORD: quantera_secret_2026
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_files:/app/staticfiles
    depends_on:
      - db
      - redis

  celery:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: celery -A config worker -l info
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_files:
